### ISSUE TITLE
Create brandbook for Alfa-Bank for Shopaholic plugin

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/partner-products-brandbook#1]
**Plugin name:** Alfa-Bank for Shopaholic
**URL:** https://alfabank.ru/sme/rko/internet-acquiring/
**Description:** Integration with the internet acquiring of Alfa-Bank.

Image requirements can be found [here](https://github.com/oc-shopaholic/partner-products-brandbook#plugins-kit).

**Icon**
- [x] icon.svg
- [x] icon-marketplace.png
- [x] icon-vkontakte.png

**Banner**
- [x] banner-marketplace.png
- [x] banner-twitter.png
- [x] banner-facebook.png
- [x] banner-vkontakte.png

**Black Friday Edition**
- [x] icon-marketplace-blackfriday.png
- [x] icon-vkontakte-blackfriday.png
- [x] banner-marketplace-blackfriday.png

**Christmas Edition**
- [x] icon-marketplace-christmas.png
- [x] icon-vkontakte-christmas.png
- [x] banner-marketplace-christmas.png

**Installs Edition**
- [x] icon-marketplace-installs.png
- [x] icon-vkontakte-installs.png
- [x] banner-marketplace-installs.png

**Comment by nastyafrosty** [comment]
[Alfabank.zip](https://github.com/oc-shopaholic/partner-products-brandbook/files/5141568/Alfabank.zip)
@lautsevich

**Comment by nastyafrosty** [comment]
![icon-marketplace](https://user-images.githubusercontent.com/41231823/91552856-274b3480-e935-11ea-8606-46507a272e8e.png)
![icon-marketplace-blackfriday](https://user-images.githubusercontent.com/41231823/91552858-27e3cb00-e935-11ea-8144-62f8ea12801d.png)
![icon-marketplace-christmas](https://user-images.githubusercontent.com/41231823/91552860-287c6180-e935-11ea-9bbf-096e0de23a47.png)
![icon-vkontakte-blackfriday](https://user-images.githubusercontent.com/41231823/91552861-287c6180-e935-11ea-941f-5b908ab181e1.png)
![icon-vkontakte-christmas](https://user-images.githubusercontent.com/41231823/91552862-2914f800-e935-11ea-9741-d865d48175db.png)
![banner-facebook](https://user-images.githubusercontent.com/41231823/91552863-2914f800-e935-11ea-9f8a-521aacfe9063.png)
![banner-marketplace](https://user-images.githubusercontent.com/41231823/91552865-29ad8e80-e935-11ea-8dfd-5ae8a664c85b.png)
![banner-marketplace-blackfriday](https://user-images.githubusercontent.com/41231823/91552868-29ad8e80-e935-11ea-9794-21ab9a3b6a0e.png)
![banner-marketplace-christmas](https://user-images.githubusercontent.com/41231823/91552869-2a462500-e935-11ea-951f-80751b919bf1.png)
![banner-twitter](https://user-images.githubusercontent.com/41231823/91552874-2a462500-e935-11ea-9d47-a0d8569c7411.png)
![banner-vkontakte](https://user-images.githubusercontent.com/41231823/91552875-2a462500-e935-11ea-8878-e3a3b802ced0.png)
![icon](https://user-images.githubusercontent.com/41231823/91552876-2adebb80-e935-11ea-9498-1fee5fa9ca0c.png)

**Comment by nastyafrosty** [comment]
![icon-marketplace-christmas](https://user-images.githubusercontent.com/41231823/91553968-efdd8780-e936-11ea-802d-01c787ffcb6c.png)
![icon-vkontakte-blackfriday](https://user-images.githubusercontent.com/41231823/91553970-f0761e00-e936-11ea-88f4-c8944ee35c03.png)
![icon-vkontakte-christmas](https://user-images.githubusercontent.com/41231823/91553973-f0761e00-e936-11ea-8c39-f16abced59c3.png)
![icon-marketplace](https://user-images.githubusercontent.com/41231823/91553975-f10eb480-e936-11ea-8ca0-492302f90652.png)
![banner-facebook](https://user-images.githubusercontent.com/41231823/91553977-f10eb480-e936-11ea-9a63-9b49e6a013af.png)
![banner-marketplace](https://user-images.githubusercontent.com/41231823/91553979-f1a74b00-e936-11ea-9d47-021a8a49f8d0.png)
![banner-marketplace-blackfriday](https://user-images.githubusercontent.com/41231823/91553982-f1a74b00-e936-11ea-99a6-52cb35dfb994.png)
![banner-marketplace-christmas](https://user-images.githubusercontent.com/41231823/91553983-f23fe180-e936-11ea-9c20-09728acf92ec.png)
![banner-twitter](https://user-images.githubusercontent.com/41231823/91553986-f23fe180-e936-11ea-8632-fb0c4741affa.png)
![banner-vkontakte](https://user-images.githubusercontent.com/41231823/91553987-f2d87800-e936-11ea-81c9-98b5358c8492.png)
![icon](https://user-images.githubusercontent.com/41231823/91553988-f2d87800-e936-11ea-8041-2530ad420588.png)

**Comment by nastyafrosty** [comment]
![banner-marketplace-installs](https://user-images.githubusercontent.com/41231823/91554730-616a0580-e938-11ea-97c7-32b008d11ef2.png)
![icon-vkontakte-installs](https://user-images.githubusercontent.com/41231823/91554734-62029c00-e938-11ea-8013-0453a52c5f5a.png)
![icon-marketplace-installs](https://user-images.githubusercontent.com/41231823/91554739-629b3280-e938-11ea-9679-ea581fd9eff3.png)

**Comment by lautsevich** [comment]
@FlusherDock1, Alpha-Bank brandbook is ready.

**Comment by FlusherDock1** [comment]
Замечательно
