### ISSUE TITLE
Create brandbook for Tinkoff for Shopaholic plugin

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/partner-products-brandbook#2]
**Plugin name:** Tinkoff for Shopaholic
**URL:** https://www.tinkoff.ru/business/internet-acquiring/
**Description:** Integration with the internet acquiring of the Tinkoff bank.

Image requirements can be found [here](https://github.com/oc-shopaholic/partner-products-brandbook#plugins-kit).

**Icon**
- [x] icon.svg
- [x] icon-marketplace.png
- [x] icon-vkontakte.png

**Banner**
- [x] banner-marketplace.png
- [x] banner-twitter.png
- [x] banner-facebook.png
- [x] banner-vkontakte.png

**Black Friday Edition**
- [x] icon-marketplace-blackfriday.png
- [x] icon-vkontakte-blackfriday.png
- [x] banner-marketplace-blackfriday.png

**Christmas Edition**
- [x] icon-marketplace-christmas.png
- [x] icon-vkontakte-christmas.png
- [x] banner-marketplace-christmas.png

**Installs Edition**
- [x] icon-marketplace-installs.png
- [x] icon-vkontakte-installs.png
- [x] banner-marketplace-installs.png

**Comment by nastyafrosty** [comment]
![1](https://user-images.githubusercontent.com/41231823/91701510-15110680-eb80-11ea-86c4-99480780b340.png)
![2](https://user-images.githubusercontent.com/41231823/91701513-15a99d00-eb80-11ea-90a0-bcbbe03fbc12.png)
@lautsevich which variant should we choose? if we leave the original logo, it's better to use black color, cause the contrast with yellow is very low. but if we make logo more "filled", we can use yellow

**Comment by nastyafrosty** [comment]
![banner-facebook](https://user-images.githubusercontent.com/41231823/91838990-077a8000-ec57-11ea-8d12-c324f2cd9ea4.png)
![banner-marketplace](https://user-images.githubusercontent.com/41231823/91838993-08abad00-ec57-11ea-99c2-fb238566c2f4.png)
![banner-marketplace-blackfriday](https://user-images.githubusercontent.com/41231823/91838995-08abad00-ec57-11ea-9000-53965b771ae0.png)
![banner-marketplace-christmas](https://user-images.githubusercontent.com/41231823/91838997-09444380-ec57-11ea-92c7-b5482ed385c0.png)
![banner-marketplace-installs](https://user-images.githubusercontent.com/41231823/91838999-09444380-ec57-11ea-9ba5-19e04877ea53.png)
![banner-twitter](https://user-images.githubusercontent.com/41231823/91839001-09dcda00-ec57-11ea-8f6d-7f4e07fe270f.png)
![banner-vkontakte](https://user-images.githubusercontent.com/41231823/91839003-09dcda00-ec57-11ea-9f45-cc56edde8be3.png)
![icon](https://user-images.githubusercontent.com/41231823/91839004-09dcda00-ec57-11ea-9e50-61b496c23c85.png)
![icon-marketplace](https://user-images.githubusercontent.com/41231823/91839005-0a757080-ec57-11ea-8a01-ce84bd7785f7.png)
![icon-marketplace-blackfriday](https://user-images.githubusercontent.com/41231823/91839008-0a757080-ec57-11ea-9bfd-de25cf57b33b.png)
![icon-marketplace-christmas](https://user-images.githubusercontent.com/41231823/91839009-0b0e0700-ec57-11ea-954e-de87092497e9.png)
![icon-marketplace-installs](https://user-images.githubusercontent.com/41231823/91839010-0b0e0700-ec57-11ea-9524-634ac51f84de.png)
![icon-vkontakte](https://user-images.githubusercontent.com/41231823/91839011-0b0e0700-ec57-11ea-9d21-11a97ae84bb7.png)
![icon-vkontakte-blackfriday](https://user-images.githubusercontent.com/41231823/91839012-0ba69d80-ec57-11ea-80c3-1f7305385e38.png)
![icon-vkontakte-christmas](https://user-images.githubusercontent.com/41231823/91839013-0ba69d80-ec57-11ea-8b7c-03ce1fb3ea3c.png)
![icon-vkontakte-installs](https://user-images.githubusercontent.com/41231823/91839014-0c3f3400-ec57-11ea-82d7-11fd5342cbc7.png)
@lautsevich

**Comment by lautsevich** [comment]
Great! Feel free to open a new PR!

**Comment by lautsevich** [comment]
@FlusherDock1, done!
