### ISSUE TITLE
Create brandbook for WayForPay for Shopaholic plugin

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/partner-products-brandbook#3]
**Plugin name:** WayForPay for Shopaholic
**URL:** https://wayforpay.com/ru
**Description:** Integration with the WayForPay internet acquiring.

Image requirements can be found [here](https://github.com/oc-shopaholic/partner-products-brandbook#plugins-kit).

**Icon**
- [x] icon.svg
- [x] icon-marketplace.png
- [x] icon-vkontakte.png

**Banner**
- [x] banner-marketplace.png
- [x] banner-twitter.png
- [x] banner-facebook.png
- [x] banner-vkontakte.png

**Black Friday Edition**
- [x] icon-marketplace-blackfriday.png
- [x] icon-vkontakte-blackfriday.png
- [x] banner-marketplace-blackfriday.png

**Christmas Edition**
- [x] icon-marketplace-christmas.png
- [x] icon-vkontakte-christmas.png
- [x] banner-marketplace-christmas.png

**Installs Edition**
- [x] icon-marketplace-installs.png
- [x] icon-vkontakte-installs.png
- [x] banner-marketplace-installs.png

**Comment by nastyafrosty** [comment]
![1](https://user-images.githubusercontent.com/41231823/91704194-ee54cf00-eb83-11ea-9aeb-2441375b8ec1.png)
@lautsevich is this variant ok?

**Comment by lautsevich** [comment]
@nastyafrosty, more than OK, I believe! =)) Go ahead!

**Comment by nastyafrosty** [comment]
![icon-marketplace-blackfriday](https://user-images.githubusercontent.com/41231823/91714691-f406e080-eb94-11ea-9721-b9a72a45f0ff.png)
![icon-marketplace-christmas](https://user-images.githubusercontent.com/41231823/91714692-f49f7700-eb94-11ea-8841-7b6af89992db.png)
![icon-marketplace-installs](https://user-images.githubusercontent.com/41231823/91714693-f49f7700-eb94-11ea-840f-118f408c63b0.png)
![icon-vkontakte-blackfriday](https://user-images.githubusercontent.com/41231823/91714694-f5380d80-eb94-11ea-8b04-35fc0bad3e30.png)
![icon-vkontakte-christmas](https://user-images.githubusercontent.com/41231823/91714695-f5380d80-eb94-11ea-9259-2b853915a732.png)
![icon-vkontakte-installs](https://user-images.githubusercontent.com/41231823/91714696-f5d0a400-eb94-11ea-8b94-754a178cf795.png)
![banner-facebook](https://user-images.githubusercontent.com/41231823/91714699-f5d0a400-eb94-11ea-9537-e4af548a3971.png)
![banner-marketplace](https://user-images.githubusercontent.com/41231823/91714700-f6693a80-eb94-11ea-8c05-ebf0f3819b5c.png)
![banner-marketplace-blackfriday](https://user-images.githubusercontent.com/41231823/91714701-f6693a80-eb94-11ea-98a2-732a41baff31.png)
![banner-marketplace-installs](https://user-images.githubusercontent.com/41231823/91714702-f6693a80-eb94-11ea-8d02-c8860782ac82.png)
![banner-twitter](https://user-images.githubusercontent.com/41231823/91714704-f701d100-eb94-11ea-91da-d99fa9b8e22c.png)
![banner-vkontakte](https://user-images.githubusercontent.com/41231823/91714705-f701d100-eb94-11ea-9d3c-0b7f90c00076.png)
![icon-marketplace](https://user-images.githubusercontent.com/41231823/91714706-f701d100-eb94-11ea-8db7-60d0efe090c5.png)

**Comment by lautsevich** [comment]
Great! Thx. Make a PR, pls.

**Comment by lautsevich** [comment]
@FlusherDock1, done! Please, take it.
